export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'



export const VOTE_PAGEINDEX = 'VOTE_PAGEINDEX'
export const VOTE_CHANGE_TYPE = 'VOTE_CHANGE_TYPE'

